# .github/actions/hello-world-action/action.yml
name: 'Hello World Action'
description: 'Prints Hello World'
author: 'Your Name'
inputs:
  who-to-greet: 
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: sh hello-world.sh
      shell: bash
