# .github/actions/helm-build-apply.yml
name: 'Helm Build and Apply'
description: 'Build and apply helm'

inputs:
  application:
    description: 'name of application like loki.yaml'
    required: true


runs:
  using: composite
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: helm-build-apply.sh ${{ inputs.application }}
      shell: bash