name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        include:
          - python-version: 3.8
            environment: development
          - python-version: 3.9
            environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover tests

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    environment: production

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    

    strategy:
      matrix:
        environment: [development, production]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Environment
        run: echo "Deploying to ${{ matrix.environment }} environment"

