name: Lower Infra Deployment
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  loki:
    name: "Loki"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'custom-helm'
        name: helmfile initialization
        uses: ./.github/actions/custom-helm-action
        with:
            application: loki.yaml
      
      - name: ouptut
        run: echo "${{ steps.custom-helm.outputs.helm_apply_required }}"


      - name: helm build and apply
        uses: ./.github/actions/helm-build-apply
        with:
            application: loki.yaml